// This code is part of Qiskit.
//
// (C) Copyright IBM 2026
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

// =====================================
// This file is automatically generated.
// =====================================

use crate::declare_fn;

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u32)]
pub enum QkExitCode {
    Success = 0,
    CInputError = 100,
    NullPointerError = 101,
    AlignmentError = 102,
    IndexError = 103,
    DuplicateIndexError = 104,
    InvalidOperationKind = 105,
    ArithmeticError = 200,
    MismatchedQubits = 201,
    ExpectedUnitary = 202,
    TargetError = 300,
    TargetInstAlreadyExists = 301,
    TargetQargMismatch = 302,
    TargetInvalidQargsKey = 303,
    TargetInvalidInstKey = 304,
    TranspilerError = 400,
    DagError = 500,
    DagComposeMismatch = 501,
    DagComposeMissingBit = 502,
    ParameterError = 600,
    ParameterNameConflict = 601,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkGate {
    GlobalPhase = 0,
    H = 1,
    I = 2,
    X = 3,
    Y = 4,
    Z = 5,
    Phase = 6,
    R = 7,
    RX = 8,
    RY = 9,
    RZ = 10,
    S = 11,
    Sdg = 12,
    SX = 13,
    SXdg = 14,
    T = 15,
    Tdg = 16,
    U = 17,
    U1 = 18,
    U2 = 19,
    U3 = 20,
    CH = 21,
    CX = 22,
    CY = 23,
    CZ = 24,
    DCX = 25,
    ECR = 26,
    Swap = 27,
    ISwap = 28,
    CPhase = 29,
    CRX = 30,
    CRY = 31,
    CRZ = 32,
    CS = 33,
    CSdg = 34,
    CSX = 35,
    CU = 36,
    CU1 = 37,
    CU3 = 38,
    RXX = 39,
    RYY = 40,
    RZZ = 41,
    RZX = 42,
    XXMinusYY = 43,
    XXPlusYY = 44,
    CCX = 45,
    CCZ = 46,
    CSwap = 47,
    RCCX = 48,
    C3X = 49,
    C3SX = 50,
    RC3X = 51,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkOperationKind {
    Gate = 0,
    Barrier = 1,
    Delay = 2,
    Measure = 3,
    Reset = 4,
    Unitary = 5,
    PauliProductMeasurement = 6,
    ControlFlow = 7,
    Unknown = 8,
    PauliProductRotation = 9,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkDelayUnit {
    S = 0,
    MS = 1,
    US = 2,
    NS = 3,
    PS = 4,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkVarsMode {
    Alike = 0,
    Captures = 1,
    Drop = 2,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkBlocksMode {
    Drop = 0,
    Keep = 1,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkExprNodeKind {
    Unary = 0,
    Binary = 1,
    Cast = 2,
    Value = 3,
    Var = 4,
    Stretch = 5,
    Index = 6,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkBinaryOpType {
    BitAnd = 1,
    BitOr = 2,
    BitXor = 3,
    LogicAnd = 4,
    LogicOr = 5,
    Equal = 6,
    NotEqual = 7,
    Less = 8,
    LessEqual = 9,
    Greater = 10,
    GreaterEqual = 11,
    ShiftLeft = 12,
    ShiftRight = 13,
    Add = 14,
    Sub = 15,
    Mul = 16,
    Div = 17,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkExprType {
    Bool = 0,
    Duration = 1,
    Float = 2,
    Uint = 3,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkUnaryOpType {
    BitNot = 1,
    LogicNot = 2,
    Negate = 3,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkDurationType {
    Dt = 0,
    Ps = 1,
    Ns = 2,
    Us = 3,
    Ms = 4,
    S = 5,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkControlFlowKind {
    Box = 0,
    BreakLoop = 1,
    ContinueLoop = 2,
    ForLoop = 3,
    IfElse = 4,
    Switch = 5,
    While = 6,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkConditionType {
    ClBit = 0,
    ClReg = 1,
    Expr = 2,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkBoxDurationKind {
    NoDuration = 0,
    Duration = 1,
    Expr = 2,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkLoopCollectionType {
    List = 0,
    Range = 1,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkLoopParamKind {
    NoLoopParam = 0,
    Parameter = 1,
    Variable = 2,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkSymbolType {
    Standalone = 0,
    Element = 1,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkDagNodeType {
    Operation = 0,
    QubitIn = 1,
    QubitOut = 2,
    ClbitIn = 3,
    ClbitOut = 4,
    VarIn = 5,
    VarOut = 6,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(u8)]
pub enum QkBitTerm {
    X = 2,
    Plus = 10,
    Minus = 6,
    Y = 3,
    Right = 11,
    Left = 7,
    Z = 1,
    Zero = 9,
    One = 5,
}

#[repr(C)]
pub struct QkControlFlowInstruction {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkCircuit {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkClassicalRegister {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkDag {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkExprNode {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkParam {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkQuantumRegister {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkObs {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkStretch {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkTarget {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkTargetEntry {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkTranspileLayout {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkTranspilerStageState {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkVF2LayoutConfiguration {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkVF2LayoutResult {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkValue {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkVar {
    _private: ::core::marker::PhantomData<(*mut u8, ::core::marker::PhantomPinned)>,
}

#[repr(C)]
pub struct QkOpCount {
    pub name: *const ::std::ffi::c_char,
    pub count: usize,
}

#[repr(C)]
pub struct QkOpCounts {
    pub data: *mut QkOpCount,
    pub len: usize,
}

#[repr(C)]
pub struct QkCircuitInstruction {
    pub name: *mut ::std::ffi::c_char,
    pub qubits: *mut u32,
    pub clbits: *mut u32,
    pub params: *mut *mut QkParam,
    pub num_qubits: u32,
    pub num_clbits: u32,
    pub num_params: u32,
}

#[repr(C)]
pub struct QkPauliProductRotation {
    pub z: *mut bool,
    pub x: *mut bool,
    pub len: usize,
    pub angle: *mut QkParam,
}

#[repr(C)]
pub struct QkPauliProductMeasurement {
    pub z: *mut bool,
    pub x: *mut bool,
    pub len: usize,
    pub flip_outcome: bool,
}

#[repr(C)]
pub struct QkCircuitDrawerConfig {
    pub bundle_cregs: bool,
    pub merge_wires: bool,
    pub fold: usize,
}

#[repr(C)]
pub struct QkExprTypeInfo {
    pub ty: QkExprType,
    pub width: u32,
}

#[repr(C)]
pub struct QkBinaryExprInfo {
    pub op: QkBinaryOpType,
    pub left: *const QkExprNode,
    pub right: *const QkExprNode,
    pub ty: QkExprTypeInfo,
    pub constant: bool,
}

#[repr(C)]
pub struct QkUnaryExprInfo {
    pub op: QkUnaryOpType,
    pub operand: *const QkExprNode,
    pub ty: QkExprTypeInfo,
    pub constant: bool,
}

#[repr(C)]
pub struct QkCastExprInfo {
    pub operand: *const QkExprNode,
    pub ty: QkExprTypeInfo,
    pub implicit: bool,
    pub constant: bool,
}

#[repr(C)]
pub struct QkIndexExprInfo {
    pub target: *const QkExprNode,
    pub index: *const QkExprNode,
    pub ty: QkExprTypeInfo,
    pub constant: bool,
}

#[repr(C)]
pub struct QkDurationInfo {
    pub ty: QkDurationType,
    pub value: QkDurationValue,
}

#[repr(C)]
pub struct QkConditionBitInfo {
    pub clbit: u32,
    pub condition: bool,
}

#[repr(C)]
pub struct QkLoopElements {
    pub elements: *const isize,
    pub len: usize,
}

#[repr(C)]
pub struct QkSymbolInfo {
    pub ty: QkSymbolType,
    pub name: *mut ::std::ffi::c_char,
    pub index: usize,
}

#[repr(C)]
pub struct QkSwitchCaseLabels {
    pub labels: *const u64,
    pub num_labels: usize,
}

#[repr(C)]
pub struct QkDagNeighbors {
    pub neighbors: *const u32,
    pub num_neighbors: usize,
}

#[repr(C)]
pub struct QkObsTerm {
    pub coeff: ::num_complex::Complex64,
    pub len: usize,
    pub bit_terms: *mut QkBitTerm,
    pub indices: *mut u32,
    pub num_qubits: u32,
}

#[repr(C)]
pub struct QkNeighbors {
    pub neighbors: *const u32,
    pub partition: *const usize,
    pub num_qubits: u32,
}

#[repr(C)]
pub struct QkSabreLayoutOptions {
    pub max_iterations: usize,
    pub num_swap_trials: usize,
    pub num_random_trials: usize,
    pub seed: u64,
}

#[repr(C)]
pub struct QkInstructionProperties {
    pub duration: f64,
    pub error: f64,
}

#[repr(C)]
pub struct QkTargetOp {
    pub op_type: QkOperationKind,
    pub name: *mut ::std::ffi::c_char,
    pub num_qubits: u32,
    pub params: *const *mut QkParam,
    pub num_params: u32,
}

#[repr(C)]
pub struct QkTranspileOptions {
    pub optimization_level: u8,
    pub seed: i64,
    pub approximation_degree: f64,
}

#[repr(C)]
pub struct QkTranspileResult {
    pub circuit: *mut QkCircuit,
    pub layout: *mut QkTranspileLayout,
}

#[repr(C)]
pub union QkDurationValue {
    pub dt: i64,
    pub time: f64,
}

declare_fn!(crate::QK_FFI_CIRCUIT[0]; qk_api_version() -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[5]; qk_circuit_new(num_qubits: u32, num_clbits: u32) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[6]; qk_quantum_register_new(num_qubits: u32, name: *const ::std::ffi::c_char) -> *mut QkQuantumRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[7]; qk_quantum_register_free(reg: *mut QkQuantumRegister));
declare_fn!(crate::QK_FFI_CIRCUIT[8]; qk_classical_register_free(reg: *mut QkClassicalRegister));
declare_fn!(crate::QK_FFI_CIRCUIT[9]; qk_classical_register_new(num_clbits: u32, name: *const ::std::ffi::c_char) -> *mut QkClassicalRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[10]; qk_circuit_add_quantum_register(circuit: *mut QkCircuit, reg: *const QkQuantumRegister));
declare_fn!(crate::QK_FFI_CIRCUIT[11]; qk_circuit_add_classical_register(circuit: *mut QkCircuit, reg: *const QkClassicalRegister));
declare_fn!(crate::QK_FFI_CIRCUIT[12]; qk_circuit_copy(circuit: *const QkCircuit) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[13]; qk_circuit_num_qubits(circuit: *const QkCircuit) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[14]; qk_circuit_num_clbits(circuit: *const QkCircuit) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[15]; qk_circuit_free(circuit: *mut QkCircuit));
declare_fn!(crate::QK_FFI_CIRCUIT[16]; qk_circuit_gate(circuit: *mut QkCircuit, gate: QkGate, qubits: *const u32, params: *const f64) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[17]; qk_gate_num_qubits(gate: QkGate) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[18]; qk_gate_num_params(gate: QkGate) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[19]; qk_circuit_measure(circuit: *mut QkCircuit, qubit: u32, clbit: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[20]; qk_circuit_reset(circuit: *mut QkCircuit, qubit: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[21]; qk_circuit_barrier(circuit: *mut QkCircuit, qubits: *const u32, num_qubits: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[22]; qk_circuit_unitary(circuit: *mut QkCircuit, matrix: *const ::num_complex::Complex64, qubits: *const u32, num_qubits: u32, check_input: bool) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[23]; qk_circuit_inst_unitary(circuit: *mut QkCircuit, index: usize, out: *mut ::num_complex::Complex64));
declare_fn!(crate::QK_FFI_CIRCUIT[24]; qk_circuit_pauli_product_rotation(circuit: *mut QkCircuit, rotation: *const QkPauliProductRotation, qubits: *const u32));
declare_fn!(crate::QK_FFI_CIRCUIT[25]; qk_circuit_inst_pauli_product_rotation(circuit: *const QkCircuit, index: usize, instruction: *mut QkPauliProductRotation) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[26]; qk_circuit_pauli_product_measurement(circuit: *mut QkCircuit, measurement: *const QkPauliProductMeasurement, qubits: *const u32, clbit: u32));
declare_fn!(crate::QK_FFI_CIRCUIT[27]; qk_circuit_inst_pauli_product_measurement(circuit: *const QkCircuit, index: usize, instruction: *mut QkPauliProductMeasurement) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[28]; qk_circuit_instruction_kind(circuit: *const QkCircuit, index: usize) -> QkOperationKind);
declare_fn!(crate::QK_FFI_CIRCUIT[29]; qk_circuit_count_ops(circuit: *const QkCircuit) -> QkOpCounts);
declare_fn!(crate::QK_FFI_CIRCUIT[30]; qk_circuit_num_instructions(circuit: *const QkCircuit) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[31]; qk_circuit_get_instruction(circuit: *const QkCircuit, index: usize, instruction: *mut QkCircuitInstruction));
declare_fn!(crate::QK_FFI_CIRCUIT[32]; qk_circuit_instruction_clear(inst: *mut QkCircuitInstruction));
declare_fn!(crate::QK_FFI_CIRCUIT[33]; qk_opcounts_clear(op_counts: *mut QkOpCounts));
declare_fn!(crate::QK_FFI_CIRCUIT[34]; qk_circuit_delay(circuit: *mut QkCircuit, qubit: u32, duration: f64, unit: QkDelayUnit) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[35]; qk_circuit_to_dag(circuit: *const QkCircuit) -> *mut QkDag);
declare_fn!(crate::QK_FFI_CIRCUIT[36]; qk_circuit_copy_empty_like(circuit: *const QkCircuit, vars_mode: QkVarsMode, blocks_mode: QkBlocksMode) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[37]; qk_circuit_num_param_symbols(circuit: *const QkCircuit) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[38]; qk_circuit_parameterized_gate(circuit: *mut QkCircuit, gate: QkGate, qubits: *const u32, params: *const *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[39]; qk_circuit_to_python(qc: *mut QkCircuit) -> *mut ::pyo3::ffi::PyObject);
declare_fn!(crate::QK_FFI_CIRCUIT[40]; qk_circuit_to_python_full(qc: *mut QkCircuit) -> *mut ::pyo3::ffi::PyObject);
declare_fn!(crate::QK_FFI_CIRCUIT[41]; qk_circuit_borrow_from_python(ob: *mut ::pyo3::ffi::PyObject) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[42]; qk_circuit_convert_from_python(object: *mut ::pyo3::ffi::PyObject, address: *mut ::std::ffi::c_void) -> ::std::ffi::c_int);
declare_fn!(crate::QK_FFI_CIRCUIT[43]; qk_quantum_register_to_python(qr: *mut QkQuantumRegister) -> *mut ::pyo3::ffi::PyObject);
declare_fn!(crate::QK_FFI_CIRCUIT[44]; qk_quantum_register_borrow_from_python(ob: *mut ::pyo3::ffi::PyObject) -> *const QkQuantumRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[45]; qk_quantum_register_convert_from_python(object: *mut ::pyo3::ffi::PyObject, address: *mut ::std::ffi::c_void) -> ::std::ffi::c_int);
declare_fn!(crate::QK_FFI_CIRCUIT[46]; qk_classical_register_to_python(cr: *mut QkClassicalRegister) -> *mut ::pyo3::ffi::PyObject);
declare_fn!(crate::QK_FFI_CIRCUIT[47]; qk_classical_register_borrow_from_python(ob: *mut ::pyo3::ffi::PyObject) -> *const QkClassicalRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[48]; qk_classical_register_convert_from_python(object: *mut ::pyo3::ffi::PyObject, address: *mut ::std::ffi::c_void) -> ::std::ffi::c_int);
declare_fn!(crate::QK_FFI_CIRCUIT[49]; qk_circuit_draw(circuit: *const QkCircuit, config: *const QkCircuitDrawerConfig) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_CIRCUIT[50]; qk_circuit_global_phase(circuit: *const QkCircuit) -> *mut QkParam);
declare_fn!(crate::QK_FFI_CIRCUIT[51]; qk_circuit_set_global_phase(circuit: *mut QkCircuit, phase: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[52]; qk_circuit_estimate_fidelity(circuit: *const QkCircuit, target: *const QkTarget) -> f64);
declare_fn!(crate::QK_FFI_CIRCUIT[53]; qk_quantum_register_name(qreg: *const QkQuantumRegister) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_CIRCUIT[54]; qk_quantum_register_num_bits(qreg: *const QkQuantumRegister) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[55]; qk_quantum_register_circuit_bits(qreg: *const QkQuantumRegister, circuit: *const QkCircuit, out_bits: *mut u32));
declare_fn!(crate::QK_FFI_CIRCUIT[56]; qk_classical_register_name(creg: *const QkClassicalRegister) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_CIRCUIT[57]; qk_classical_register_num_bits(creg: *const QkClassicalRegister) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[58]; qk_classical_register_circuit_bits(creg: *const QkClassicalRegister, circuit: *const QkCircuit, out_bits: *mut u32));
declare_fn!(crate::QK_FFI_CIRCUIT[59]; qk_circuit_num_quantum_registers(circuit: *const QkCircuit) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[60]; qk_circuit_get_quantum_register(circuit: *const QkCircuit, qreg_idx: usize) -> *const QkQuantumRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[61]; qk_circuit_num_classical_registers(circuit: *const QkCircuit) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[62]; qk_circuit_get_classical_register(circuit: *const QkCircuit, creg_idx: usize) -> *const QkClassicalRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[63]; qk_circuit_get_control_flow_instruction(circuit: *const QkCircuit, inst_idx: usize, parent_cf: *const QkControlFlowInstruction) -> *mut QkControlFlowInstruction);
declare_fn!(crate::QK_FFI_CIRCUIT[64]; qk_control_flow_instruction_free(cf_inst: *mut QkControlFlowInstruction));
declare_fn!(crate::QK_FFI_CIRCUIT[65]; qk_control_flow_kind(cf_inst: *const QkControlFlowInstruction) -> QkControlFlowKind);
declare_fn!(crate::QK_FFI_CIRCUIT[66]; qk_control_flow_num_blocks(cf_inst: *const QkControlFlowInstruction) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[67]; qk_control_flow_block_circuit(cf_inst: *const QkControlFlowInstruction, block_idx: usize) -> *const QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[68]; qk_control_flow_qubit_map(cf_inst: *const QkControlFlowInstruction) -> *const u32);
declare_fn!(crate::QK_FFI_CIRCUIT[69]; qk_control_flow_clbit_map(cf_inst: *const QkControlFlowInstruction) -> *const u32);
declare_fn!(crate::QK_FFI_CIRCUIT[70]; qk_control_flow_condition_type(cf_inst: *const QkControlFlowInstruction) -> QkConditionType);
declare_fn!(crate::QK_FFI_CIRCUIT[71]; qk_control_flow_condition_bit_info(cf_inst: *const QkControlFlowInstruction) -> QkConditionBitInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[72]; qk_control_flow_condition_reg_cond_bit_width(cf_inst: *const QkControlFlowInstruction) -> u64);
declare_fn!(crate::QK_FFI_CIRCUIT[73]; qk_control_flow_condition_reg(cf_inst: *const QkControlFlowInstruction) -> *const QkClassicalRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[74]; qk_control_flow_condition_reg_cond_uint(cf_inst: *const QkControlFlowInstruction) -> u64);
declare_fn!(crate::QK_FFI_CIRCUIT[75]; qk_control_flow_condition_expr(cf_inst: *const QkControlFlowInstruction) -> *const QkExprNode);
declare_fn!(crate::QK_FFI_CIRCUIT[76]; qk_control_flow_box_duration_kind(cf_inst: *const QkControlFlowInstruction) -> QkBoxDurationKind);
declare_fn!(crate::QK_FFI_CIRCUIT[77]; qk_control_flow_box_duration_val_info(cf_inst: *const QkControlFlowInstruction) -> QkDurationInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[78]; qk_control_flow_box_duration_expr(cf_inst: *const QkControlFlowInstruction) -> *const QkExprNode);
declare_fn!(crate::QK_FFI_CIRCUIT[79]; qk_control_flow_loop_collection_type(cf_inst: *const QkControlFlowInstruction) -> QkLoopCollectionType);
declare_fn!(crate::QK_FFI_CIRCUIT[80]; qk_control_flow_loop_elements(cf_inst: *const QkControlFlowInstruction) -> QkLoopElements);
declare_fn!(crate::QK_FFI_CIRCUIT[81]; qk_control_flow_loop_range(cf_inst: *const QkControlFlowInstruction, out_start: *mut i64, out_stop: *mut i64, out_step: *mut i64));
declare_fn!(crate::QK_FFI_CIRCUIT[82]; qk_control_flow_loop_param_kind(cf_inst: *const QkControlFlowInstruction) -> QkLoopParamKind);
declare_fn!(crate::QK_FFI_CIRCUIT[83]; qk_control_flow_loop_symbol_info(cf_inst: *const QkControlFlowInstruction) -> QkSymbolInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[84]; qk_control_flow_loop_variable(cf_inst: *const QkControlFlowInstruction) -> *const QkVar);
declare_fn!(crate::QK_FFI_CIRCUIT[85]; qk_control_flow_switch_target_type(cf_inst: *const QkControlFlowInstruction) -> QkConditionType);
declare_fn!(crate::QK_FFI_CIRCUIT[86]; qk_control_flow_switch_target_bit(cf_inst: *const QkControlFlowInstruction) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[87]; qk_control_flow_switch_target_register(cf_inst: *const QkControlFlowInstruction) -> *const QkClassicalRegister);
declare_fn!(crate::QK_FFI_CIRCUIT[88]; qk_control_flow_switch_target_expr(cf_inst: *const QkControlFlowInstruction) -> *const QkExprNode);
declare_fn!(crate::QK_FFI_CIRCUIT[89]; qk_control_flow_switch_num_cases(cf_inst: *const QkControlFlowInstruction) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[90]; qk_control_flow_switch_is_case_default(cf_inst: *const QkControlFlowInstruction, case_idx: usize) -> bool);
declare_fn!(crate::QK_FFI_CIRCUIT[91]; qk_control_flow_switch_case_labels_bit_width(cf_inst: *const QkControlFlowInstruction, case_idx: usize) -> u64);
declare_fn!(crate::QK_FFI_CIRCUIT[92]; qk_control_flow_switch_case_labels_uint(cf_inst: *const QkControlFlowInstruction, case_idx: usize) -> QkSwitchCaseLabels);
declare_fn!(crate::QK_FFI_CIRCUIT[93]; qk_control_flow_switch_case_labels_clear(labels: *mut QkSwitchCaseLabels));
declare_fn!(crate::QK_FFI_CIRCUIT[105]; qk_dag_new() -> *mut QkDag);
declare_fn!(crate::QK_FFI_CIRCUIT[106]; qk_dag_add_quantum_register(dag: *mut QkDag, reg: *const QkQuantumRegister));
declare_fn!(crate::QK_FFI_CIRCUIT[107]; qk_dag_add_classical_register(dag: *mut QkDag, reg: *const QkClassicalRegister));
declare_fn!(crate::QK_FFI_CIRCUIT[108]; qk_dag_num_qubits(dag: *const QkDag) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[109]; qk_dag_num_clbits(dag: *const QkDag) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[110]; qk_dag_num_op_nodes(dag: *const QkDag) -> usize);
declare_fn!(crate::QK_FFI_CIRCUIT[111]; qk_dag_node_type(dag: *const QkDag, node: u32) -> QkDagNodeType);
declare_fn!(crate::QK_FFI_CIRCUIT[112]; qk_dag_qubit_in_node(dag: *const QkDag, qubit: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[113]; qk_dag_qubit_out_node(dag: *const QkDag, qubit: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[114]; qk_dag_clbit_in_node(dag: *const QkDag, clbit: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[115]; qk_dag_clbit_out_node(dag: *const QkDag, clbit: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[116]; qk_dag_wire_node_value(dag: *const QkDag, node: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[117]; qk_dag_op_node_num_qubits(dag: *const QkDag, node: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[118]; qk_dag_op_node_num_clbits(dag: *const QkDag, node: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[119]; qk_dag_op_node_num_params(dag: *const QkDag, node: u32) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[120]; qk_dag_op_node_qubits(dag: *const QkDag, node: u32) -> *const u32);
declare_fn!(crate::QK_FFI_CIRCUIT[121]; qk_dag_op_node_clbits(dag: *const QkDag, node: u32) -> *const u32);
declare_fn!(crate::QK_FFI_CIRCUIT[122]; qk_dag_apply_gate(dag: *mut QkDag, gate: QkGate, qubits: *const u32, params: *const f64, front: bool) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[123]; qk_dag_apply_measure(dag: *mut QkDag, qubit: u32, clbit: u32, front: bool) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[124]; qk_dag_apply_reset(dag: *mut QkDag, qubit: u32, front: bool) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[125]; qk_dag_apply_barrier(dag: *mut QkDag, qubits: *const u32, num_qubits: u32, front: bool) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[126]; qk_dag_apply_unitary(dag: *mut QkDag, matrix: *const ::num_complex::Complex64, qubits: *const u32, num_qubits: u32, front: bool) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[127]; qk_dag_op_node_gate_op(dag: *const QkDag, node: u32, out_params: *mut f64) -> QkGate);
declare_fn!(crate::QK_FFI_CIRCUIT[128]; qk_dag_op_node_unitary(dag: *const QkDag, node: u32, out: *mut ::num_complex::Complex64));
declare_fn!(crate::QK_FFI_CIRCUIT[129]; qk_dag_op_node_kind(dag: *const QkDag, node: u32) -> QkOperationKind);
declare_fn!(crate::QK_FFI_CIRCUIT[130]; qk_dag_successors(dag: *const QkDag, node: u32) -> QkDagNeighbors);
declare_fn!(crate::QK_FFI_CIRCUIT[131]; qk_dag_predecessors(dag: *const QkDag, node: u32) -> QkDagNeighbors);
declare_fn!(crate::QK_FFI_CIRCUIT[132]; qk_dag_neighbors_clear(neighbors: *mut QkDagNeighbors));
declare_fn!(crate::QK_FFI_CIRCUIT[133]; qk_dag_get_instruction(dag: *const QkDag, index: u32, instruction: *mut QkCircuitInstruction));
declare_fn!(crate::QK_FFI_CIRCUIT[134]; qk_dag_compose(dag: *mut QkDag, other: *const QkDag, qubits: *const u32, clbits: *const u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[135]; qk_dag_free(dag: *mut QkDag));
declare_fn!(crate::QK_FFI_CIRCUIT[136]; qk_dag_to_circuit(dag: *const QkDag) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[137]; qk_dag_topological_op_nodes(dag: *const QkDag, out_order: *mut u32));
declare_fn!(crate::QK_FFI_CIRCUIT[138]; qk_dag_substitute_node_with_dag(dag: *mut QkDag, node: u32, replacement: *const QkDag));
declare_fn!(crate::QK_FFI_CIRCUIT[139]; qk_dag_copy_empty_like(dag: *const QkDag, vars_mode: QkVarsMode, blocks_mode: QkBlocksMode) -> *mut QkDag);
declare_fn!(crate::QK_FFI_CIRCUIT[140]; qk_dag_to_python(dag: *mut QkDag) -> *mut ::pyo3::ffi::PyObject);
declare_fn!(crate::QK_FFI_CIRCUIT[141]; qk_dag_borrow_from_python(ob: *mut ::pyo3::ffi::PyObject) -> *mut QkDag);
declare_fn!(crate::QK_FFI_CIRCUIT[142]; qk_dag_convert_from_python(object: *mut ::pyo3::ffi::PyObject, address: *mut ::std::ffi::c_void) -> ::std::ffi::c_int);
declare_fn!(crate::QK_FFI_CIRCUIT[143]; qk_dag_replace_block_with_unitary(dag: *mut QkDag, num_block_ids: u32, block_ids: *const u32, matrix: *const ::num_complex::Complex64, num_qubits: u32, qubits: *const u32, cycle_check: bool) -> u32);
declare_fn!(crate::QK_FFI_CIRCUIT[144]; qk_dag_substitute_node_with_unitary(dag: *mut QkDag, node: u32, matrix: *const ::num_complex::Complex64, num_qubits: u32));
declare_fn!(crate::QK_FFI_CIRCUIT[145]; qk_dag_global_phase(dag: *const QkDag) -> *mut QkParam);
declare_fn!(crate::QK_FFI_CIRCUIT[146]; qk_dag_set_global_phase(dag: *mut QkDag, phase: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[205]; qk_param_new_symbol(name: *const ::std::ffi::c_char) -> *mut QkParam);
declare_fn!(crate::QK_FFI_CIRCUIT[206]; qk_param_zero() -> *mut QkParam);
declare_fn!(crate::QK_FFI_CIRCUIT[207]; qk_param_free(param: *mut QkParam));
declare_fn!(crate::QK_FFI_CIRCUIT[208]; qk_param_from_double(value: f64) -> *mut QkParam);
declare_fn!(crate::QK_FFI_CIRCUIT[209]; qk_param_from_complex(value: ::num_complex::Complex64) -> *mut QkParam);
declare_fn!(crate::QK_FFI_CIRCUIT[210]; qk_param_copy(param: *const QkParam) -> *mut QkParam);
declare_fn!(crate::QK_FFI_CIRCUIT[211]; qk_param_str(param: *const QkParam) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_CIRCUIT[212]; qk_param_add(out: *mut QkParam, lhs: *const QkParam, rhs: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[213]; qk_param_sub(out: *mut QkParam, lhs: *const QkParam, rhs: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[214]; qk_param_mul(out: *mut QkParam, lhs: *const QkParam, rhs: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[215]; qk_param_div(out: *mut QkParam, num: *const QkParam, den: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[216]; qk_param_pow(out: *mut QkParam, base: *const QkParam, pow: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[217]; qk_param_sin(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[218]; qk_param_cos(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[219]; qk_param_tan(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[220]; qk_param_asin(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[221]; qk_param_acos(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[222]; qk_param_atan(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[223]; qk_param_log(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[224]; qk_param_exp(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[225]; qk_param_abs(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[226]; qk_param_sign(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[227]; qk_param_neg(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[228]; qk_param_conjugate(out: *mut QkParam, src: *const QkParam) -> QkExitCode);
declare_fn!(crate::QK_FFI_CIRCUIT[229]; qk_param_equal(lhs: *const QkParam, rhs: *const QkParam) -> bool);
declare_fn!(crate::QK_FFI_CIRCUIT[230]; qk_param_as_real(param: *const QkParam) -> f64);
declare_fn!(crate::QK_FFI_CIRCUIT[255]; qk_circuit_library_iqp(num_qubits: u32, interactions: *const i64, check_input: bool) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[256]; qk_circuit_library_random_iqp(num_qubits: u32, seed: i64) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[257]; qk_circuit_library_quantum_volume(num_qubits: u32, depth: usize, seed: i64) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[258]; qk_circuit_library_suzuki_trotter(op: *const QkObs, order: u32, reps: u32, time: f64, preserve_order: bool, insert_barriers: bool) -> *mut QkCircuit);
declare_fn!(crate::QK_FFI_CIRCUIT[259]; qk_pauli_product_rotation_clear(inst: *mut QkPauliProductRotation));
declare_fn!(crate::QK_FFI_CIRCUIT[260]; qk_pauli_product_measurement_clear(inst: *mut QkPauliProductMeasurement));
declare_fn!(crate::QK_FFI_CIRCUIT[305]; qk_expr_kind(expr: *const QkExprNode) -> QkExprNodeKind);
declare_fn!(crate::QK_FFI_CIRCUIT[306]; qk_expr_binary_info(expr: *const QkExprNode) -> QkBinaryExprInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[307]; qk_expr_unary_info(expr: *const QkExprNode) -> QkUnaryExprInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[308]; qk_expr_cast_info(expr: *const QkExprNode) -> QkCastExprInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[309]; qk_expr_index_info(expr: *const QkExprNode) -> QkIndexExprInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[310]; qk_expr_as_value(expr: *const QkExprNode) -> *const QkValue);
declare_fn!(crate::QK_FFI_CIRCUIT[311]; qk_expr_as_var(expr: *const QkExprNode) -> *const QkVar);
declare_fn!(crate::QK_FFI_CIRCUIT[312]; qk_expr_as_stretch(expr: *const QkExprNode) -> *const QkStretch);
declare_fn!(crate::QK_FFI_CIRCUIT[313]; qk_value_type_info(value: *const QkValue) -> QkExprTypeInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[314]; qk_value_duration_info(value: *const QkValue) -> QkDurationInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[315]; qk_value_float(value: *const QkValue) -> f64);
declare_fn!(crate::QK_FFI_CIRCUIT[316]; qk_value_uint(value: *const QkValue) -> u64);
declare_fn!(crate::QK_FFI_CIRCUIT[317]; qk_value_bool(value: *const QkValue) -> bool);
declare_fn!(crate::QK_FFI_CIRCUIT[318]; qk_var_name(var: *const QkVar) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_CIRCUIT[319]; qk_var_type_info(var: *const QkVar) -> QkExprTypeInfo);
declare_fn!(crate::QK_FFI_CIRCUIT[320]; qk_stretch_name(stretch: *const QkStretch) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_TRANSPILE[0]; qk_transpile(qc: *const QkCircuit, target: *const QkTarget, options: *const QkTranspileOptions, result: *mut QkTranspileResult, error: *mut *mut ::std::ffi::c_char) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[1]; qk_transpiler_default_options() -> QkTranspileOptions);
declare_fn!(crate::QK_FFI_TRANSPILE[2]; qk_transpile_stage_init(dag: *mut QkDag, target: *const QkTarget, options: *const QkTranspileOptions, state: *mut *mut QkTranspilerStageState, error: *mut *mut ::std::ffi::c_char) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[3]; qk_transpile_stage_routing(dag: *mut QkDag, target: *const QkTarget, options: *const QkTranspileOptions, state: *mut QkTranspilerStageState, error: *mut *mut ::std::ffi::c_char) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[4]; qk_transpile_stage_optimization(dag: *mut QkDag, target: *const QkTarget, options: *const QkTranspileOptions, error: *mut *mut ::std::ffi::c_char, state: *mut QkTranspilerStageState) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[5]; qk_transpile_stage_translation(dag: *mut QkDag, target: *const QkTarget, options: *const QkTranspileOptions, error: *mut *mut ::std::ffi::c_char) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[6]; qk_transpile_stage_layout(dag: *mut QkDag, target: *const QkTarget, options: *const QkTranspileOptions, state: *mut *mut QkTranspilerStageState, error: *mut *mut ::std::ffi::c_char) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[20]; qk_neighbors_is_all_to_all(neighbors: *const QkNeighbors) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[21]; qk_neighbors_from_target(target: *const QkTarget, neighbors: *mut QkNeighbors) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[22]; qk_neighbors_clear(neighbors: *mut QkNeighbors));
declare_fn!(crate::QK_FFI_TRANSPILE[35]; qk_transpile_layout_num_input_qubits(layout: *const QkTranspileLayout) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[36]; qk_transpile_layout_num_output_qubits(layout: *const QkTranspileLayout) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[37]; qk_transpile_layout_initial_layout(layout: *const QkTranspileLayout, filter_ancillas: bool, initial_layout: *mut u32) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[38]; qk_transpile_layout_output_permutation(layout: *const QkTranspileLayout, output_permutation: *mut u32) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[39]; qk_transpile_layout_final_layout(layout: *const QkTranspileLayout, filter_ancillas: bool, final_layout: *mut u32));
declare_fn!(crate::QK_FFI_TRANSPILE[40]; qk_transpile_layout_generate_from_mapping(original_dag: *const QkDag, target: *const QkTarget, qubit_mapping: *const u32) -> *mut QkTranspileLayout);
declare_fn!(crate::QK_FFI_TRANSPILE[41]; qk_transpile_layout_free(layout: *mut QkTranspileLayout));
declare_fn!(crate::QK_FFI_TRANSPILE[42]; qk_transpile_layout_to_python(layout: *const QkTranspileLayout, circuit: *const QkCircuit) -> *mut ::pyo3::ffi::PyObject);
declare_fn!(crate::QK_FFI_TRANSPILE[50]; qk_transpile_state_new(state: *mut *mut QkTranspilerStageState));
declare_fn!(crate::QK_FFI_TRANSPILE[51]; qk_transpile_state_free(state: *mut QkTranspilerStageState));
declare_fn!(crate::QK_FFI_TRANSPILE[52]; qk_transpile_state_layout(state: *mut QkTranspilerStageState) -> *mut QkTranspileLayout);
declare_fn!(crate::QK_FFI_TRANSPILE[53]; qk_transpile_state_layout_set(state: *mut QkTranspilerStageState, layout: *mut QkTranspileLayout));
declare_fn!(crate::QK_FFI_TRANSPILE[150]; qk_target_new(num_qubits: u32) -> *mut QkTarget);
declare_fn!(crate::QK_FFI_TRANSPILE[151]; qk_target_num_qubits(target: *const QkTarget) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[152]; qk_target_dt(target: *const QkTarget) -> f64);
declare_fn!(crate::QK_FFI_TRANSPILE[153]; qk_target_set_dt(target: *mut QkTarget, dt: f64) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[154]; qk_target_granularity(target: *const QkTarget) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[155]; qk_target_set_granularity(target: *mut QkTarget, granularity: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[156]; qk_target_min_length(target: *const QkTarget) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[157]; qk_target_set_min_length(target: *mut QkTarget, min_length: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[158]; qk_target_pulse_alignment(target: *const QkTarget) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[159]; qk_target_set_pulse_alignment(target: *mut QkTarget, pulse_alignment: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[160]; qk_target_acquire_alignment(target: *const QkTarget) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[161]; qk_target_set_acquire_alignment(target: *mut QkTarget, acquire_alignment: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[162]; qk_target_copy(target: *mut QkTarget) -> *mut QkTarget);
declare_fn!(crate::QK_FFI_TRANSPILE[163]; qk_target_free(target: *mut QkTarget));
declare_fn!(crate::QK_FFI_TRANSPILE[164]; qk_target_add_instruction(target: *mut QkTarget, target_entry: *mut QkTargetEntry) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[165]; qk_target_update_property(target: *mut QkTarget, instruction: QkGate, qargs: *mut u32, num_qubits: u32, duration: f64, error: f64) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[166]; qk_target_num_instructions(target: *const QkTarget) -> usize);
declare_fn!(crate::QK_FFI_TRANSPILE[167]; qk_target_instruction_supported(target: *const QkTarget, operation_name: *const ::std::ffi::c_char, qargs: *const u32, params: *mut *mut QkParam) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[168]; qk_target_op_index(target: *const QkTarget, name: *const ::std::ffi::c_char) -> usize);
declare_fn!(crate::QK_FFI_TRANSPILE[169]; qk_target_op_name(target: *const QkTarget, index: usize) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_TRANSPILE[170]; qk_target_op_num_properties(target: *const QkTarget, index: usize) -> usize);
declare_fn!(crate::QK_FFI_TRANSPILE[171]; qk_target_op_qargs_index(target: *const QkTarget, op_idx: usize, qargs: *const u32) -> usize);
declare_fn!(crate::QK_FFI_TRANSPILE[172]; qk_target_op_qargs(target: *const QkTarget, op_idx: usize, qarg_idx: usize, qargs_out: *mut *mut u32, qargs_len: *mut u32));
declare_fn!(crate::QK_FFI_TRANSPILE[173]; qk_target_op_props(target: *const QkTarget, op_idx: usize, qarg_idx: usize, inst_props: *mut QkInstructionProperties));
declare_fn!(crate::QK_FFI_TRANSPILE[174]; qk_target_op_get(target: *const QkTarget, index: usize, out_op: *mut QkTargetOp));
declare_fn!(crate::QK_FFI_TRANSPILE[175]; qk_target_op_gate(target: *const QkTarget, index: usize) -> QkGate);
declare_fn!(crate::QK_FFI_TRANSPILE[176]; qk_target_op_clear(op: *mut QkTargetOp));
declare_fn!(crate::QK_FFI_TRANSPILE[177]; qk_target_borrow_from_python(ob: *mut ::pyo3::ffi::PyObject) -> *mut QkTarget);
declare_fn!(crate::QK_FFI_TRANSPILE[178]; qk_target_convert_from_python(object: *mut ::pyo3::ffi::PyObject, address: *mut ::std::ffi::c_void) -> ::std::ffi::c_int);
declare_fn!(crate::QK_FFI_TRANSPILE[200]; qk_target_entry_new(operation: QkGate) -> *mut QkTargetEntry);
declare_fn!(crate::QK_FFI_TRANSPILE[201]; qk_target_entry_new_measure() -> *mut QkTargetEntry);
declare_fn!(crate::QK_FFI_TRANSPILE[202]; qk_target_entry_new_reset() -> *mut QkTargetEntry);
declare_fn!(crate::QK_FFI_TRANSPILE[203]; qk_target_entry_new_fixed(operation: QkGate, params: *mut f64, name: *const ::std::ffi::c_char) -> *mut QkTargetEntry);
declare_fn!(crate::QK_FFI_TRANSPILE[204]; qk_target_entry_num_properties(entry: *const QkTargetEntry) -> usize);
declare_fn!(crate::QK_FFI_TRANSPILE[205]; qk_target_entry_free(entry: *mut QkTargetEntry));
declare_fn!(crate::QK_FFI_TRANSPILE[206]; qk_target_entry_add_property(entry: *mut QkTargetEntry, qargs: *mut u32, num_qubits: u32, duration: f64, error: f64) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[207]; qk_target_entry_set_name(entry: *mut QkTargetEntry, name: *const ::std::ffi::c_char) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[250]; qk_transpiler_pass_elide_permutations(dag: *mut QkDag) -> *mut QkTranspileLayout);
declare_fn!(crate::QK_FFI_TRANSPILE[251]; qk_transpiler_pass_check_gate_direction(dag: *const QkDag, target: *const QkTarget) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[252]; qk_transpiler_pass_gate_direction(dag: *mut QkDag, target: *const QkTarget));
declare_fn!(crate::QK_FFI_TRANSPILE[253]; qk_transpiler_pass_optimize_1q_sequences(dag: *mut QkDag, target: *const QkTarget));
declare_fn!(crate::QK_FFI_TRANSPILE[254]; qk_transpiler_pass_remove_diagonal_gates_before_measure(dag: *mut QkDag));
declare_fn!(crate::QK_FFI_TRANSPILE[255]; qk_transpiler_pass_remove_identity_equivalent(dag: *mut QkDag, target: *const QkTarget, approximation_degree: f64));
declare_fn!(crate::QK_FFI_TRANSPILE[256]; qk_transpiler_pass_split_2q_unitaries(dag: *mut QkDag, requested_fidelity: f64, split_swaps: bool) -> *mut QkTranspileLayout);
declare_fn!(crate::QK_FFI_TRANSPILE[257]; qk_transpiler_pass_2q_peephole_optimization(dag: *mut QkDag, target: *const QkTarget, approximation_degree: f64));
declare_fn!(crate::QK_FFI_TRANSPILE[350]; qk_transpiler_pass_standalone_basis_translator(circuit: *mut QkCircuit, target: *const QkTarget, min_qubits: usize));
declare_fn!(crate::QK_FFI_TRANSPILE[351]; qk_transpiler_pass_standalone_commutative_cancellation(circuit: *mut QkCircuit, target: *const QkTarget, approximation_degree: f64) -> QkExitCode);
declare_fn!(crate::QK_FFI_TRANSPILE[352]; qk_transpiler_pass_standalone_consolidate_blocks(circuit: *mut QkCircuit, target: *const QkTarget, approximation_degree: f64, force_consolidate: bool));
declare_fn!(crate::QK_FFI_TRANSPILE[353]; qk_transpiler_pass_standalone_elide_permutations(circuit: *mut QkCircuit) -> *mut QkTranspileLayout);
declare_fn!(crate::QK_FFI_TRANSPILE[354]; qk_transpiler_pass_standalone_check_gate_direction(circuit: *const QkCircuit, target: *const QkTarget) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[355]; qk_transpiler_pass_standalone_gate_direction(circuit: *mut QkCircuit, target: *const QkTarget));
declare_fn!(crate::QK_FFI_TRANSPILE[356]; qk_transpiler_pass_standalone_inverse_cancellation(circuit: *mut QkCircuit));
declare_fn!(crate::QK_FFI_TRANSPILE[357]; qk_transpiler_pass_standalone_optimize_1q_sequences(circuit: *mut QkCircuit, target: *const QkTarget));
declare_fn!(crate::QK_FFI_TRANSPILE[358]; qk_transpiler_pass_standalone_remove_diagonal_gates_before_measure(circuit: *mut QkCircuit));
declare_fn!(crate::QK_FFI_TRANSPILE[359]; qk_transpiler_pass_standalone_remove_identity_equivalent(circuit: *mut QkCircuit, target: *const QkTarget, approximation_degree: f64));
declare_fn!(crate::QK_FFI_TRANSPILE[360]; qk_transpiler_pass_standalone_sabre_layout(circuit: *mut QkCircuit, target: *const QkTarget, options: *const QkSabreLayoutOptions) -> *mut QkTranspileLayout);
declare_fn!(crate::QK_FFI_TRANSPILE[361]; qk_transpiler_pass_standalone_split_2q_unitaries(circuit: *mut QkCircuit, requested_fidelity: f64, split_swaps: bool) -> *mut QkTranspileLayout);
declare_fn!(crate::QK_FFI_TRANSPILE[362]; qk_transpiler_pass_standalone_unitary_synthesis(circuit: *mut QkCircuit, target: *const QkTarget, min_qubits: usize, approximation_degree: f64));
declare_fn!(crate::QK_FFI_TRANSPILE[363]; qk_transpiler_pass_standalone_vf2_layout_average(circuit: *const QkCircuit, target: *const QkTarget, config: *const QkVF2LayoutConfiguration, strict_direction: bool) -> *mut QkVF2LayoutResult);
declare_fn!(crate::QK_FFI_TRANSPILE[364]; qk_transpiler_pass_standalone_vf2_layout_exact(circuit: *const QkCircuit, target: *const QkTarget, config: *const QkVF2LayoutConfiguration) -> *mut QkVF2LayoutResult);
declare_fn!(crate::QK_FFI_TRANSPILE[365]; qk_transpiler_pass_standalone_convert_to_pauli_rotations(circuit: *mut QkCircuit));
declare_fn!(crate::QK_FFI_TRANSPILE[366]; qk_transpiler_pass_standalone_litinski_transformation(circuit: *mut QkCircuit, fix_clifford: bool));
declare_fn!(crate::QK_FFI_TRANSPILE[367]; qk_transpiler_pass_standalone_2q_peephole_optimization(circuit: *mut QkCircuit, target: *const QkTarget, approximation_degree: f64));
declare_fn!(crate::QK_FFI_TRANSPILE[450]; qk_sabre_layout_options_default() -> QkSabreLayoutOptions);
declare_fn!(crate::QK_FFI_TRANSPILE[455]; qk_vf2_layout_result_has_match(layout: *const QkVF2LayoutResult) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[456]; qk_vf2_layout_result_has_improvement(layout: *const QkVF2LayoutResult) -> bool);
declare_fn!(crate::QK_FFI_TRANSPILE[457]; qk_vf2_layout_result_map_virtual_qubit(layout: *const QkVF2LayoutResult, qubit: u32) -> u32);
declare_fn!(crate::QK_FFI_TRANSPILE[458]; qk_vf2_layout_result_free(layout: *mut QkVF2LayoutResult));
declare_fn!(crate::QK_FFI_TRANSPILE[459]; qk_vf2_layout_configuration_new() -> *mut QkVF2LayoutConfiguration);
declare_fn!(crate::QK_FFI_TRANSPILE[460]; qk_vf2_layout_configuration_free(config: *mut QkVF2LayoutConfiguration));
declare_fn!(crate::QK_FFI_TRANSPILE[461]; qk_vf2_layout_configuration_set_call_limit(config: *mut QkVF2LayoutConfiguration, before: i64, after: i64));
declare_fn!(crate::QK_FFI_TRANSPILE[462]; qk_vf2_layout_configuration_set_time_limit(config: *mut QkVF2LayoutConfiguration, limit: f64));
declare_fn!(crate::QK_FFI_TRANSPILE[463]; qk_vf2_layout_configuration_set_max_trials(config: *mut QkVF2LayoutConfiguration, limit: u64));
declare_fn!(crate::QK_FFI_TRANSPILE[464]; qk_vf2_layout_configuration_set_shuffle_seed(config: *mut QkVF2LayoutConfiguration, seed: u64));
declare_fn!(crate::QK_FFI_TRANSPILE[465]; qk_vf2_layout_configuration_set_score_initial(config: *mut QkVF2LayoutConfiguration, score_initial: bool));
declare_fn!(crate::QK_FFI_QI[0]; qk_obs_zero(num_qubits: u32) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[1]; qk_obs_identity(num_qubits: u32) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[2]; qk_obs_new(num_qubits: u32, num_terms: u64, num_bits: u64, coeffs: *mut ::num_complex::Complex64, bit_terms: *mut QkBitTerm, indices: *mut u32, boundaries: *mut usize) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[3]; qk_obs_free(obs: *mut QkObs));
declare_fn!(crate::QK_FFI_QI[4]; qk_obs_add_term(obs: *mut QkObs, cterm: *const QkObsTerm) -> QkExitCode);
declare_fn!(crate::QK_FFI_QI[5]; qk_obs_term(obs: *mut QkObs, index: u64, out: *mut QkObsTerm) -> QkExitCode);
declare_fn!(crate::QK_FFI_QI[6]; qk_obs_num_terms(obs: *const QkObs) -> usize);
declare_fn!(crate::QK_FFI_QI[7]; qk_obs_num_qubits(obs: *const QkObs) -> u32);
declare_fn!(crate::QK_FFI_QI[8]; qk_obs_len(obs: *const QkObs) -> usize);
declare_fn!(crate::QK_FFI_QI[9]; qk_obs_coeffs(obs: *mut QkObs) -> *mut ::num_complex::Complex64);
declare_fn!(crate::QK_FFI_QI[10]; qk_obs_indices(obs: *mut QkObs) -> *mut u32);
declare_fn!(crate::QK_FFI_QI[11]; qk_obs_boundaries(obs: *mut QkObs) -> *mut usize);
declare_fn!(crate::QK_FFI_QI[12]; qk_obs_bit_terms(obs: *mut QkObs) -> *mut QkBitTerm);
declare_fn!(crate::QK_FFI_QI[13]; qk_obs_multiply(obs: *const QkObs, coeff: *const ::num_complex::Complex64) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[14]; qk_obs_multiply_inplace(obs: *mut QkObs, coeff: *const ::num_complex::Complex64));
declare_fn!(crate::QK_FFI_QI[15]; qk_obs_add(left: *const QkObs, right: *const QkObs) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[16]; qk_obs_add_inplace(left: *mut QkObs, right: *const QkObs));
declare_fn!(crate::QK_FFI_QI[17]; qk_obs_scaled_add(left: *const QkObs, right: *const QkObs, factor: *const ::num_complex::Complex64) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[18]; qk_obs_scaled_add_inplace(left: *mut QkObs, right: *const QkObs, factor: *const ::num_complex::Complex64));
declare_fn!(crate::QK_FFI_QI[19]; qk_obs_compose(first: *const QkObs, second: *const QkObs) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[20]; qk_obs_compose_map(first: *const QkObs, second: *const QkObs, qargs: *const u32) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[21]; qk_obs_apply_layout(obs: *mut QkObs, layout: *const u32, num_qubits: u32) -> QkExitCode);
declare_fn!(crate::QK_FFI_QI[22]; qk_obs_canonicalize(obs: *const QkObs, tol: f64) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[23]; qk_obs_copy(obs: *const QkObs) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[24]; qk_obs_equal(obs: *const QkObs, other: *const QkObs) -> bool);
declare_fn!(crate::QK_FFI_QI[25]; qk_obs_str(obs: *const QkObs) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_QI[26]; qk_str_free(string: *mut ::std::ffi::c_char));
declare_fn!(crate::QK_FFI_QI[27]; qk_obsterm_str(term: *const QkObsTerm) -> *mut ::std::ffi::c_char);
declare_fn!(crate::QK_FFI_QI[28]; qk_bitterm_label(bit_term: QkBitTerm) -> u8);
declare_fn!(crate::QK_FFI_QI[29]; qk_obs_to_python(obs: *mut QkObs) -> *mut ::pyo3::ffi::PyObject);
declare_fn!(crate::QK_FFI_QI[30]; qk_obs_borrow_from_python(ob: *mut ::pyo3::ffi::PyObject) -> *mut QkObs);
declare_fn!(crate::QK_FFI_QI[31]; qk_obs_convert_from_python(object: *mut ::pyo3::ffi::PyObject, address: *mut ::std::ffi::c_void) -> ::std::ffi::c_int);
