[package]
name = "qiskit-sys-bindgen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
qiskit-bindgen.workspace = true
pyo3 = {workspace = true, optional = true}
cbindgen.workspace = true
anyhow.workspace = true
hashbrown.workspace = true
qiskit-cext-vtable.workspace = true

[features]
python_binding = ["dep:pyo3"]
