// This code is part of Qiskit.
//
// (C) Copyright IBM 2026
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at https://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.
pub mod render;

use std::{fs, path::{Path, PathBuf}, process::Command};
use qiskit_bindgen::generate_bindings;

fn rust_pyo3_ffi_root() -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "qiskit", "pyo3-ffi"].iter().collect()
}

fn rust_pyo3_ffi_files() -> anyhow::Result<Vec<PathBuf>> {
    let root = rust_pyo3_ffi_root();
    let output = Command::new("cargo")
        .arg("package")
        .arg("--list") // Only list the files in the output, don't do any packaging.
        .arg("--allow-dirty") // Permit `git` to be dirty, since this isn't a true packaging op.
        .current_dir(&root)
        .output()?;
    anyhow::ensure!(
        output.status.success(),
        "'cargo package' listing failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let mut out = Vec::new();
    // Technically the paths are probably `OsString`, but that's just fiddly to handle properly.  We
    // can fix it if we need to.
    for line in String::from_utf8(output.stdout)?.lines() {
        let path = line.parse::<PathBuf>()?;
        // Some of the files listed by `cargo package` are ones that would be generated by the
        // packaging command, so if they don't exist, don't add them.
        if root.join(&path).is_file() {
            out.push(path);
        }
    }
    Ok(out)
}

pub fn install_rust_pyo3_ffi(
    bindings: &cbindgen::Bindings,
    install_path: impl AsRef<Path>,
) -> anyhow::Result<()> {
    let mut items = render::ir::Items::default();
    items.add_from_cbindgen(bindings)?;

    let install_path = install_path.as_ref();
    fs::create_dir_all(install_path)?;

    // First copy over the template repository verbatim...
    let crate_root = rust_pyo3_ffi_root();
    for file in rust_pyo3_ffi_files()? {
        if let Some(parent) = file.parent() {
            fs::create_dir_all(install_path.join(parent))?;
        }
        fs::copy(crate_root.join(&file), install_path.join(&file))?;
    }

    // ... and then overwrite the generated file.
    items.export(fs::File::create(install_path.join("src").join("ffi.rs"))?)?;
    Ok(())
}